swagger: "2.0"
info:
  title: Blog API
  description: >
    This is the backend to a blog app that allows users to register, create blogs, comment and like blogs...
  version: "1.0.0"
host: "127.0.0.1:5000"
schemas:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
